# Generated by Django 5.2.6 on 2025-09-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterhelp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
